import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Providers } from '@/store/provider';
import { Toaster } from '@/components/ui/sonner';
import MainLayout from '@/layouts/MainLayout';
import NotificationProvider from './providers/NotificationProvider';
import { ChatProvider } from './providers/ChatProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <NotificationProvider>
            <ChatProvider>
              <MainLayout>{children}</MainLayout>
            </ChatProvider>
          </NotificationProvider>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
